Repository Avis-Drone-Labs/FGCS, pull requests merged in 2025-03, with the labels that each got.

#528 Moved SettingsModal to main.jsx
  gcs/src/dashboard.jsx
  gcs/src/main.jsx
Labels: alpha-0.1.8-patch

#530 Fixed spotlight on mac
  gcs/src/components/SingleRunWrapper.jsx
  gcs/src/components/dashboard/map.jsx
  gcs/src/components/fla/graph.jsx
  gcs/src/components/settingsModal.jsx
  gcs/src/components/spotlight/actions.jsx
  gcs/src/components/spotlight/commandHandler.js
  gcs/src/components/spotlight/spotlight.jsx
  gcs/src/components/toolbar/toolbar.jsx
  gcs/src/fla.jsx
  gcs/src/helpers/settings.js
  gcs/src/helpers/settingsProvider.jsx
  gcs/src/main.jsx
Labels: alpha-0.1.8-patch

#539 Fixing kush's branch
  gcs/src/components/dashboard/map.jsx
Labels: alpha-0.1.9

#549 Alpha 0.1.9/532 params and config message
  gcs/src/components/noDroneConnected.jsx
  gcs/src/config.jsx
  gcs/src/graphs.jsx
  gcs/src/params.jsx
Labels: bug, alpha-0.1.9

#555 Alpha 0.1.9/544 Support for displaying multiple batteries
  gcs/src/components/dashboard/telemetry.jsx
  gcs/src/dashboard.jsx
Labels: enhancement, alpha-0.1.9
